package com.dyk1323.booklogs.data.backup

import kotlinx.serialization.Serializable

/**
 * docs/PLAN.md "백업/복원" — the full-data JSON envelope written by [BackupExporter] and read back by
 * [BackupImporter]. Room's autogenerated PKs are included as-is (not reassigned) so FK relationships
 * (bookId, readingRoundId) stay intact on import — this is a "restore onto a fresh device" shape, not
 * a merge. [schemaVersion] is a slot for a future JSON-level upgrade mapper; there's only ever been
 * version 1 so far, so no mapping exists yet.
 */
@Serializable
data class BackupEnvelope(
    val schemaVersion: Int = CURRENT_SCHEMA_VERSION,
    val exportedAt: Long,
    val books: List<BookBackupDto>,
    val rounds: List<ReadingRoundBackupDto>,
    val logs: List<ReadingLogBackupDto>,
    val quotes: List<QuoteBackupDto>,
    val reviews: List<ReviewBackupDto>,
) {
    companion object {
        const val CURRENT_SCHEMA_VERSION = 1
    }
}

@Serializable
data class BookBackupDto(
    val id: Long,
    val isbn: String?,
    val title: String,
    val author: String?,
    val publisher: String?,
    val coverImageUrl: String?,
    val totalPages: Int?,
    val status: String,
    val format: String,
    val genre: String?,
    val country: String?,
    val createdAt: Long,
)

@Serializable
data class ReadingRoundBackupDto(
    val id: Long,
    val bookId: Long,
    val roundNumber: Int,
    val startedAt: Long,
    val finishedAt: Long?,
    val endReason: String?,
)

@Serializable
data class ReadingLogBackupDto(
    val id: Long,
    val bookId: Long,
    val readingRoundId: Long,
    val currentPage: Int,
    val logDateEpochDay: Long,
    val loggedAt: Long,
)

@Serializable
data class QuoteBackupDto(
    val id: Long,
    val bookId: Long,
    val text: String,
    val pageNumber: Int?,
    val pageNumberEnd: Int?,
    val createdAt: Long,
)

@Serializable
data class ReviewBackupDto(
    val id: Long,
    val bookId: Long,
    val readingRoundId: Long,
    val content: String,
    val rating: Int?,
    val createdAt: Long,
)
